title = "no42"
baseURL = "https://blog.no42.org"
theme = "bilberry-hugo-theme"

enableRobotsTXT = true

# Change to one of your content languages definded at the end.
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = "UA-73787628-1"

# Enable / Disable comments on the articles via Disqus.
#disqusShortname ="bilberry-hugo-theme"

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "" # set a favicon icon

  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "Ronny Trommer"
  description = "Private blog around tech and live."
  keywords = "blog,personal,responsive,search,font awesome,pages,posts,multilingual,highlight.js,syntax highlighting,premium,shortcuts"

  # How many articles should be displayed at once?
  paginate = 10

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = false

  # Header configuration
  # your subtitle if you want to use any
  # subtitle = "... search for answer?"

  # if you want to use gravatar for the header image
  gravatarEMail = "ronny@no42.org"

  # set an path to the image file you want to use | overwrites gravatar
  customImage = ""

  # always display the top navigation (with pages and search) on non-mobile screens
  permanentTopNav = false

  # show a language chooser in the header
  showHeaderLanguageChooser = true

  # credits line configuration
  copyrightBy = "by Lednerb"
  copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
  copyrightYearOverride = "2018"
  copyrightUrl = "https://github.com/Lednerb"
  creditsText = ""
  creditsUrl = "https://github.com/Lednerb/bilberry-hugo-theme"

  # social media profile urls for the footer links
  showSocialMedia = true
  facebook   = ""
  twitter    = "https://twitter.com/indigo423"
  googleplus = ""
  pinterest  = ""
  instagram  = ""
  tumblr     = ""
  youtube    = ""
  vimeo      = ""
  github     = "https://github.com/indigo423"
  xing       = "https://www.xing.com/profile/Ronny_Trommer"
  linkedin   = "https://www.linkedin.com/in/ronnytrommer/"

# customize your available languages for your multi-langual site
# or delete the [Languages] blog to use the theme with only one supported language
[Languages]
  [Languages.en]
    weight = 1
  [Languages.de]
    weight = 2
    title = "no42"

# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON" ]
  page = [ "HTML" ]

