title = "no42"
# Add an trailing slash to ensure that all fonts render correctly.
baseURL = "https://blog.no42.org/"
theme = "bilberry-hugo-theme"

enableRobotsTXT = true

# Change to one of your content languages definded at the end.
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
#googleAnalytics = "UA-73787628-1"

# Enable / Disable comments on the articles via Disqus.
#disqusShortname ="bilberry-hugo-theme"

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "" # set a favicon icon

  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "Ronny Trommer"
  description = "Private blog around tech and live."
  keywords = "blog,personal,responsive,search,font awesome,pages,posts,multilingual,highlight.js,syntax highlighting,premium,shortcuts"

  # How many articles should be displayed at once?
  paginate = 10

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = false

  # Style configuration
  # set the width of your site's content
  siteWidth = "900px"

  # let hugo automatically resize and crop your images to the correct sizes
  resizeImages = true

  # Header configuration
  # your subtitle if you want to use any
  subtitle = "... search for answer?"

  # if you want to use gravatar for the header image
  gravatarEMail = "ronny@no42.org"

  # set an path to the image file you want to use | overwrites gravatar
  customImage = "/images/gravatar.jpg"

  # always display the top navigation (with pages and search) on non-mobile screens
  permanentTopNav = false

  # show a language chooser in the header
  showHeaderLanguageChooser = false

  # Content configuration
  # Enable an optional pinned page to display at the top of the index
  # pinnedPost = "/content/github/"
  # Set to true to pin only to the first page, false to all pages
  # pinOnlyToFirstPage = true

  # enable automatical localization of the article's PublishedDate with momentjs
  enableMomentJs = true

  # customize the date format | only works if momentjs is disabled | only works with English month names
  # you can customize it with the options you find here:
  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02"

  # display the estimated reading time for an article
  showReadingTime = true

# Footer configuration
  showFooter = true

  # How many articles should be displayed at latest posts in the footer?
  # Set to -1 to hide the 'Latest Posts' column
  amountLatestPostsInFooter = 10

  # How many categories should be displayed in the footer section?
  # Set to -1 to hide the 'Categories' column
  amountCategoriesInFooter = 10

  # show a language chooser in the header
  showFooterLanguageChooser = false

  # social media profile urls for the footer links
  showSocialMedia = true

  # credits line configuration
  copyrightBy = "by Ronny Trommer"
  copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
  copyrightYearOverride = "2020"
  copyrightUrl = "https://github.com/indigo423"
  creditsText = ""
  creditsUrl = "https://github.com/Lednerb/bilberry-hugo-theme"

  facebook   = ""
  twitter    = "https://twitter.com/indigo423"
  googleplus = ""
  pinterest  = ""
  instagram  = ""
  tumblr     = ""
  youtube    = ""
  vimeo      = ""
  github     = "https://github.com/indigo423"
  xing       = "https://www.xing.com/profile/Ronny_Trommer"
  linkedin   = "https://www.linkedin.com/in/ronnytrommer/"

# customize your available languages for your multi-langual site
# or delete the [Languages] blog to use the theme with only one supported language
[Languages]
  [Languages.en]
    weight = 1
  [Languages.de]
    weight = 2
    title = "no42"

# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]
