baseURL = "https://blog.no42.org"
languageCode = "en-us"
title = "... search for answer"
theme = "HugoMDL"
MetaDataFormat = "yaml"
googleAnalytics = "UA-73787628-1"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = true
  [privacy.speakerDeck]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[permalinks]
	page = "/:title/"
	about = "/:filename/"

[params]
  author = "Ronny Trommer"
  avatar = "/images/avatar.png"
  background = "/images/background.jpg"
  description = "A place to publish my incomprehensible ramblings" #meta description
  image = "/images/avatar-192x210.png" #for frontpage profile card
  mdlPrimary = "cyan"
  mdlSecondary = "red"
  website = "https://blog.no42.org"
  email = "ronny@no42.org"
  twitter = "https://twitter.com/indigo423"
  github = "https://github.com/indigo423"
  linkedin = "https://www.linkedin.com/in/ronnytrommer/"
  xing = "https://www.xing.com/profile/Ronny_Trommer"
  copyrightyear = "2018"
  frontpageposts = 6 #number of post cards to display on frontpage

# Fully customizable header menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Articles"
  url = "/post/"
  weight = -180
[[menu.main]]
  name = "Projects"
  url = "/project/"
  weight = -160
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = "-140"
[[menu.main]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = "-140"
